[package]
name = "energy-dao"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "0.39.4"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "0.39.4"

[dependencies.farm]
path = "../../mx-exchange-sc/dex/farm"

[dependencies.farm-with-locked-rewards]
path = "../../mx-exchange-sc/dex/farm-with-locked-rewards"

[dependencies.farm-staking]
path = "../../mx-exchange-sc/farm-staking/farm-staking"

[dependencies.farm-staking-proxy]
path = "../../mx-exchange-sc/farm-staking/farm-staking-proxy"

[dependencies.pair]
path = "../../mx-exchange-sc/dex/pair"

[dependencies.energy-factory]
path = "../../mx-exchange-sc/locked-asset/energy-factory"

[dependencies.fees-collector]
path = "../../mx-exchange-sc/energy-integration/fees-collector"

[dependencies.locked-token-wrapper]
path = "../../mx-exchange-sc/locked-asset/locked-token-wrapper"

[dependencies.simple-lock]
path = "../../mx-exchange-sc/locked-asset/simple-lock"

[dependencies.common_structs]
path="../../mx-exchange-sc/common/common_structs"

[dependencies.mergeable]
path="../../mx-exchange-sc/common/traits/mergeable"

[dependencies.pausable]
path="../../mx-exchange-sc/common/modules/pausable"

[dependencies.utils]
path="../../mx-exchange-sc/common/modules/utils"

[dependencies.sc_whitelist_module]
path="../../mx-exchange-sc/common/modules/sc_whitelist_module"

[dependencies.token_send]
path="../../mx-exchange-sc/common/modules/token_send"

[dependencies.farm_token]
path="../../mx-exchange-sc/common/modules/farm/farm_token"

[dependencies.locking_module]
path="../../mx-exchange-sc/common/modules/locking_module"

[dependencies.config]
path="../../mx-exchange-sc/common/modules/farm/config"

[dependencies.energy-query]
path = "../../mx-exchange-sc/energy-integration/common-modules/energy-query"

[dependencies.farm-boosted-yields]
path = "../../mx-exchange-sc/energy-integration/farm-boosted-yields"

[dependencies.legacy_token_decode_module]
path="../../mx-exchange-sc/common/modules/legacy_token_decode_module"

[dependencies.lkmex-transfer]
path = "../../mx-exchange-sc/locked-asset/lkmex-transfer"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.4"
