[package]
name = "proxies"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "=0.50.5"

[dependencies.common_structs]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "c061a85"
