[package]
name = "farm-extra-rewards-wrapper"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.farm]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.farm-with-locked-rewards]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.config]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.farm_token]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.rewards]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.contexts]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.farm_base_impl]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.token_send]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.pausable]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.permissions_module]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.common_structs]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.fixed-supply-token]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.mergeable]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.unwrappable]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.math]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.utils]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dependencies.auto-farm]
path = "../auto-farm"

[dev-dependencies.tests-common]
path = "../tests-common"
features = ["enable-tests-common"]

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
hex-literal = "0.3.4"

[dependencies.multiversx-sc]
version = "=0.44.0"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.44.0"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.44.0"

[dev-dependencies.energy-factory]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"

[dev-dependencies.sc_whitelist_module]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "bd02b83"
