gateway = 'https://devnet-gateway.multiversx.com'
wegld_address = "erd1qqqqqqqqqqqqqpgqpv09kfzry5y4sj05udcngesat07umyj70n4sa2c0rp"
router_address = "erd1qqqqqqqqqqqqqpgqa7hv0nahgsl8tz0psat46x0tchm0wuyc0n4s6q28ad"
random_address = "erd19azy5vlq343un82cqz03744vmta9ya8l5xwj3ywz7r8m8pkttd0syhkffa"
egld_mex_pair_address = "erd1qqqqqqqqqqqqqpgqzw0d0tj25qme9e4ukverjjjqle6xamay0n4s5r0v9g"
egld_mex_farm_address = "erd1qqqqqqqqqqqqqpgq3chrzjdg3gu40zt6kes6w62cyz8tes6k0n4ssk3hj4"
egld_usdc_pair_address = "erd1qqqqqqqqqqqqqpgqtqfhy99su9xzjjrq59kpzpp25udtc9eq0n4sr90ax6"
egld_utk_pair_address = "erd1qqqqqqqqqqqqqpgq4zafu6rzdw7fj07hjh5tkm68jsaj7hl60n4s8py4ra"
egld_utk_farm_address = "erd1qqqqqqqqqqqqqpgql7rysqgxxzhykg3j6vccnx4003z2mcl80n4ste3jh8"
egld_one_pair_address = "erd1qqqqqqqqqqqqqpgq9xg595f0kwek2yd54kz6atkv06r9ujnx0n4s2ymns9"
metastaking_utk_address = "erd1qqqqqqqqqqqqqpgqpuerryertp2jx2xyec67pcp6j9hgmp9x0n4sl8w8kw"
farm_staking_utk_address = "erd1qqqqqqqqqqqqqpgqjepe36adjtqu0plg6w7mf8yywegl0g3q0n4svr28gf"