[package]
name = "auto-pos-creator"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "=0.43.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.43.2"

[dependencies.auto-farm]
path = "../auto-farm"

[dependencies.farm]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.farm-with-locked-rewards]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.farm-staking]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.farm-staking-proxy]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.pair]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.energy-factory]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.common_structs]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.mergeable]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.utils]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.energy-query]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.legacy_token_decode_module]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dependencies.lkmex-transfer]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
hex-literal = "0.3.4"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.43.2"

[dev-dependencies.tests-common]
path = "../tests-common"
features = ["enable-tests-common"]

[dev-dependencies.pausable]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"

[dev-dependencies.sc_whitelist_module]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "7f25a72"
