[package]
name = "auto-farm"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "=0.38.0"
features = [ "esdt-token-payment-legacy-decode" ]

[dependencies.elrond-wasm-modules]
version = "=0.38.0"

[dev-dependencies.elrond-wasm-debug]
version = "=0.38.0"

# Farm dependencies
[dependencies]
farm = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
farm-with-locked-rewards = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
farm-staking = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
farm-staking-proxy = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }

# Other SCs
pair = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
energy-factory = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
fees-collector = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }

# Other SCs - different repos
metabonding = { git = "https://github.com/multiversx/mx-metabonding-sc", rev = "7a1dd32" }

# Common modules/types
common_structs = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
mergeable = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
utils = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
energy-query = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
legacy_token_decode_module = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
lkmex-transfer = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
hex-literal = "0.3.4"

# Dependencies needed for tests
simple-lock = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
farm-boosted-yields = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
config = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
locking_module = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
farm_token = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
pausable = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
sc_whitelist_module = { git = "https://github.com/multiversx/mx-exchange-sc", rev = "6f8aeda" }
