name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v3.1.0
    with:
      rust-toolchain: nightly-2023-12-11
      coverage-args: --ignore-filename-regex='/.cargo/git' --output ./coverage.md
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
