name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v2.3.1
    with:
      rust-toolchain: nightly-2023-12-11
      vmtools-version: v1.5.24
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  # TEMPORARY: until https://github.com/multiversx/mx-sdk-rs/pull/1587 is merged and released
  test_coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-12-11
          target: wasm32-unknown-unknown

      - name: Install prerequisites
        run: |
          rustup component add llvm-tools-preview
          dirname $(find ~/.rustup -name llvm-cov) >> $GITHUB_PATH
          echo $(dirname $(find ~/.rustup -name llvm-cov))
          cargo install --git https://github.com/multiversx/mx-sdk-rs --branch "fix/coverage-fail-if-file-not-in-root"
      - name: Run tests and generate report
        env:
          RUSTFLAGS: ""
        run: |
          sc-meta test-coverage --output ./coverage.md
      - name: Upload the report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.md

      - name: Find the comment containing the report
        id: fc
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Coverage Summary"

      - name: Create or update the report comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ./coverage.md
          edit-mode: replace